### BUSI 521<br>Rice University <br>Spring 2025


#### Instructor

[Kerry Back](http://kerryback.com)
<br>
J. Howard Creekmore Professor of Finance and Professor of Economics<br>
<a href="mailto:kerryback@gmail.com">kerryback@gmail.com</a>


#### Meeting Schedule

TTh 2:30 -- 3:45<br>
1/14/2024 -- 4/24/2024


#### Textbook

[Asset Pricing and Portfolio Choice Theory](https://www.amazon.com/Portfolio-Financial-Management-Association-Synthesis/product-reviews/0190241144/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews), Oxford University Press, 2nd Edition, 2017.

#### Course Description

This course is an introduction to asset pricing and portfolio choice theory. This is the foundation for the ‘investments’ branch of finance. Understanding
how assets are priced is also important for issuing entities, like corporations, so asset
pricing is also part of the foundation for corporate finance. Of course, prices are determined by supply and demand. We take supply (a topic in corporate finance) as given in
this course and study demand (portfolio choice).

Uncertainty and time are the two key elements of portfolio choice. We will start with
single-period models and then move to dynamic models in both discrete and continuous
time. We’ll develop the theory of dynamic programming in continuous time and use it to
study portfolio choice and some corporate investment decisions. Dynamic programming
and other aspects of the mathematics of uncertainty in continuous time are useful in
other areas of economics and finance as well.

The middle part of the course will cover various topics that are of continuing research interest, and students will make presentations.

#### Course Calendar

This is a cross-listed course between the Jones School and the School of Social Sciences.  We will follow the School of Social Sciences academic calendar.  We meet TTh from 2:30-3:45 commencing January 14.  The last class day is April 24.  Per the university calendar, there will be no class on February 13 or on March 18 and March 20 (spring break).
The final exam will be during exam week.

#### Course Schedule 

1. Fundamentals of asset pricing (Jan 14 - Feb 25)
   a. Preferences, FOC, and discount factors (Chapters 1--3)
   b. Mean-variance analysis and factor picing (Chapters 5 & 6)
   c. Equilibrium, efficiency, and representative investors (Chapters 4 & 7)
2. Topics (student presentations, Feb 27 - Mar 13)
   a. Heterogenous beliefs and short sale constraints (Chapter 21)
   b. Bubbles (Chapter 21)
   c. Bayesian learning (Chapter 22)
   d. Rational expectations equilibria (Chapter 22)
   e. Glosten-Milgrom and Kyle models (Chapter 24)
   f. Glosten model of limit-order markets (Chapter 24)
   g. Common value auctions (Chapter 24)
   h. Allais paradox and betweenness preferences (Chapter 25)
   i. Generalized disappointment aversion (Chapter 25)
   j. Ellsberg paradox and ambiguity aversion (Chapter 25)
3. Continuous time methods and applications (Mar 25 - Apr 24)
   a. Brownian motion and stochastic calculus (Chapter 12)
   b. Dynamic programming (Chapters 9, 14, & 20)
   c. Optimal timing problems (Chapters 15 & 19)
   d. Bayesian learning in continuous time (Chapter 23)

#### Class Presentations

The topics listed above will be assigned to students one-to-one.  In addition to the textbook material, each student should draw heavily from at least one published paper, either a seminal paper on the topic or an application.  Presentations should be roughly 20 minutes plus Q&A.

#### Grading

Grades will be based on class participation, individual homework assignments, class presentations, and a final exam.  Late homeworks will not be accepted, but I will drop the lowest homework score.

#### Honor Code

The Rice University Honor Code applies to all work in this course. The intent of the
Honor Code in general and specifically in this course is to ensure that each student claims
and receives credit for their own efforts. The intent is not to limit the valuable exchange
of ideas through discussion among fellow students. The atmosphere at Rice University
must be one of academic and personal integrity. Any suspected violations of the Honor
Code are submitted to the Rice University Honor Council.

#### Disability Accommodations

Any student with a disability requiring accommodations in this class should contact me
after contacting the Disabled Student Services office

