## Sample Midterm Questions<br>Asset Pricing / Financial Economics I<br>Rice University

1.  Assume there are three states of the world that are equally likely.  There are two assets with prices $p_1=p_2=1$.  The payoffs of the first asset across the three states of the world are $(1,2,1)$.  The payoffs of the second asset across the three states of the world are $(0,1,3)$.  
    (a) Describe the one-dimensional family of state price vectors.
    (b) Find the SDF that is spanned by the assets.
2.  Assume there is a risk-free asset.  Derive the first-order condition for a portfolio to be on the mean-variance frontier.  Explain why the first-order condition implies a factor model for returns.
3.  Assume there is a representative investor with constant relative risk aversion $\rho \neq 1$.  Let $c_0$ denote aggregate consumption at date 0 and let $\tilde{c}_1$ denote aggregate consumption at date $1$.  Assume $\log \tilde{c}_1$ is normally distributed with mean $\log c_0 + \mu$ and variance $\sigma^2$.  
    (a) Derive a formula for $\log R_f$.  
    (b) Explain (in terms of the demand to borrow and market clearing) why $\log R_f$ is larger when $\mu$ is larger and larger when $\sigma$ is smaller.
    (c) Why is the effect of $\rho$ on $\log R_f$ ambiguous?
4.  Assume all investors have linear risk tolerance with the same cautiousness parameter.  Explain why fact (a) below implies (b) and (c).  Along the way, explain the concepts referenced in the facts.
    (a) Sharing rules are affine.
    (b) A competitive equilibrium is Pareto optimal as long as there is a risk-free asset (markets do not need to be complete).
    (c) There is two-fund separation.
5. Consider an investor who seeks to maximize
$$E \left[\sum_{t=0}^T \delta^t u(c_t)\right]$$
where
$$u(c) = \frac{1}{1-\rho}c^{1-\rho}$$
subject to the intertemporal budget constraint and subject to the terminal constraint $C_T \leq W_T$'.  Assume returns are iid.  Let $J_t(w)$ denote the value function. Define
$$B = \max_\pi E\left[\frac{1}{1-\rho}(\pi'R_T)^{1-\rho}\right]\,.$$
Show that the optimal portfolio at date $T-1$ is the portfolio that achieves this maximum, and show that
$$J_{T-1}(w) = \frac{1}{1-\rho}A_{T-1}w^{1-\rho}$$
for some constant $A_{T-1}$.
6.  Assume there is a risk-free asset.  Let $\widetilde{\mathbf{R}}$ denote the vector of risky asset returns, let $\mu$ denote the mean of $\widetilde{\mathbf{R}}$,  and let $\Sigma$ denote the covariance matrix of $\widetilde{\mathbf{R}}$.  Let $\iota$ denote a vector of 1's.  
    (a) Show that the following random variable is an SDF.
$$
\frac{1}{R_f} + \left(\iota -\frac{1}{R_f}\mu\right)'\Sigma^{-1}(\widetilde{\mathbf{R}}-\mu)\,.
$$
    (b) The random variable in part (a) is spanned by the assets, so it is the payoff of a portfolio (that may include the risk-free asset).  If we divide by the payoff by the cost of the portfolio, we obtain a return.  Thus, the random variable is proportional to a return.  Show that in fact it is proportional to a return $\pi'\widetilde{\mathbf{R}} + (1-\iota'\pi)R_f$ on the mean-variance frontier.  You can use without proof any facts that you know about the mean-variance frontier.
7.  Assume there is a representative investor with constant relative risk aversion $\rho$ and discount factor $\delta$.  Assume the change in log consumption is normally distributed with mean $\mu$ and standard deviation $\sigma$.  
    (a) Derive a formula for the risk-free return in terms of $\delta$, $\rho$, $\mu$, and $\sigma$.
    (b) Explain why the risk-free return is higher when $\mu$ is higher and lower when $\sigma$ is higher.
8.  Assume there is a risk-free asset and multiple risky assets with joint normal returns. Derive the optimal portfolio for an investor with CARA utility.
9.  Assume there are $n$ assets and $k$ states of the world. Let $X$ denote the $n \times k$ matrix of asset payoffs (so $x_{ij}$ is the payoff of the $i$th asset in the $j$th state).  Assume the Law of One Price holds and the market is complete.  Derive the unique state price vector and explain the derivation.
10.  Assume there is a risk-free asset.  Let $\widetilde{\mathbf{R}}$ denote the vector of risky asset returns, let $\mu$ denote the mean of $\widetilde{\mathbf{R}}$,  and let $\Sigma$ denote the covariance matrix of $\widetilde{\mathbf{R}}$.  Let $\iota$ denote a vector of 1's.  
    (a) Show that the following random variable is an SDF.
$$
\frac{1}{R_f} + \left(\iota -\frac{1}{R_f}\mu\right)'\Sigma^{-1}(\widetilde{\mathbf{R}}-\mu)\,.
$$
    (b) Let $\widetilde{m}$ be any SDF.  Explain why the random variable in the part(a) equals the orthogonal projection of $\widetilde{m}$ onto the span of the returns.
11.  Derive the tangency portfolio.  Explain what assumption you need to ensure that the tangency portfolio exists.
12.  Let $\tilde X = (\tilde x_1, \ldots,  \tilde x_k)$ denote a vector of random variables.  Suppose there exists a constant $a$ and a vector $b$ such that $a+b' \tilde X$ is an SDF.  Show that there is a factor pricing model with $\tilde X$ as the vector of factors.
13.  Assume there is a risk-free asset and a representative investor with CRRA utility.  Let $\tilde R_m$ denote the market return.  Derive a generalization of the CAPM of the following form:  for each asset $i$,
$$E[ \tilde R_i]-R_f = \gamma_i \bigg(E[ \tilde R_m]-R_f\bigg)$$
where $\gamma_i$ is a generalization of the market beta of asset $i$.  Give an explicit formula for $\gamma_i$.
14.  Suppose all investors have log utility and suppose $( \tilde w_1,\ldots, \tilde w_H)$ is a Pareto optimal allocation of market wealth $\tilde w_m$.  Show that each investor's wealth $\tilde w_h$ is an affine function of $\tilde w_m$.
15.  Assume there are four equally probable states of the world, a risk-free asset with return $R_f=1.5$, and two risky assets with the following payoffs:

|  | State 1 | State 2 | State 3 | State 4 |
| --- | --- | --- | --- | --- |
| $\tilde{x}_1$: | 3 | 3 | 1 | 1 |
| $\tilde{x}_2$: | 1 | 5 | 2 | 4 |

The prices of the two risky assets are $p_1 = 1$ and $p_2=2$. 
Show that the random variable having the following values in each state is an SDF.

 | State 1 | State 2 | State 3 | State 4 |
| --- | --- | --- | --- |
|1/3 | 1/3 | 1 | 1 |

16.  Suppose there are two risk-averse investors and three states of the world.  Suppose that the equilibrium end-of-period wealths of the two investors are as follows. Can we tell whether the market is complete? Explain.

 |  | State 1 | State 2 | State 3 |
| --- | --- | --- | --- |
| $\tilde{w}_1$: | 1 | 4 | 3 |
| $\tilde{w}_2$: | 2 | 3 | 5 |


17.  Consider a single-period model with a risk-free asset and a single risky asset.  Let $\phi(w)$ denote the optimal investment in the risky asset for an investor when the investor's initial wealth is $w$.  Under what circumstance is $\phi'(w)>0$?
18. Define two-fund separation.  What assumption on investor preferences implies two-fund separation?
19.  Let $\tilde{m}$ be an SDF and define a probability $Q$ by $Q(A) = R_f E[\tilde{m}1_A]$ for each event $A$.  Show that the return $\tilde{R}$ of each asset must satisfy
$E^*[\tilde{R}] = R_f$, where $E^*$ denotes expectation relative to $Q$.
20. Derive the global minimum variance portfolio.
21.  Suppose $\tilde{m}$ is an SDF and there are constants $a$ and $b$ such that $a+b\tilde{m}$ is a return.  The return has two important properties.  What are they?  
22.  Assume there is a risk-free asset.  Derive a first-order condition for a return to be on the mean-variance frontier.  Explain how this condition relates to factor pricing.
23.  Assume the CAPM holds, and let $\tilde{R}_m$ denote the market return.  There are constants $a$ and $b$ such that $a-b\tilde{R}_m$ is an SDF.  Calculate $a$ and $b$.
24.  Suppose there is a single-factor pricing model in which the factor is an excess return.  Show that the factor risk premium is the expected excess return.
25.  Suppose there is a factor pricing model in which the factors are macroeconomic variables---GDP growth, etc.  Explain why there must be a factor pricing model in which the factors are returns, and explain how the returns relate to the macroeconomic variables.
26.  Assume there is a representative investor with constant relative risk aversion $\rho$.  Assume there is a riskfree asset, and let $\tilde{R}_m$ denote the market return.  Derive the following formula for the risk premium of each asset:
$$E[\tilde{R}] - R_f = \frac{E[\tilde{R}_m]-R_f}{cov(\tilde{R}_m,\tilde{R}_m^{-\rho})}cov\left(\tilde{R},\tilde{R}_m^{-\rho}\right)\,.$$
27.  In a single-period model, assume there is a representative investor with constant relative risk aversion $\rho$.  Assume that the logarithm of aggregate consumption is normally distributed with mean $\mu$ and variance $\sigma^2$.  Show that
$$\log E[\tilde{R}_m] - \log R_f = \rho \sigma^2\,.$$
28.  What is the equity premium puzzle?
29.  Suppose there is a representative investor with discount factor $\delta$ and constant relative risk aversion $\rho$.  Assume that consumption growth $C_{t+1}/C_t$ is an iid sequence.  Show that the market return is 
$$R_{m,t+1} = \frac{1}{\nu} \cdot \frac{C_{t+1}}{C_t}\,,$$
where
$$\nu = \delta E\left[\left(\frac{C_{t+1}}{C_t}\right)^{1-\rho}\right]\,.$$
30.  Consider an investor with constant relative risk aversion in an infinite-horizon discrete-time model.  Suppose there is a single state variable $X$.  Assume the investor has no labor income $Y_t$.  Show that  
$$J(w,x) = \frac{1}{1-\rho}w^{1-\rho}f(x)$$
satisfies the Bellman equation for some function $f$.
31.  Assume there are three states of the world that are equally likely.  There are two assets with prices $p_1=p_2=1$.  The payoffs of the first asset across the three states of the world are $(1,2,1)$.  The payoffs of the second asset across the three states of the world are $(0,1,3)$.  
    (a) Describe the one-dimensional family of state price vectors.    
    (b) Find the SDF that is spanned by the assets.

32.  Explain the meaning of the following and prove it. Clearly state definitions of
terms and any assumptions you make. “Risk premia depend on covariances with
an SDF.”
33.  Assume there are n risky assets (not necessarily joint normal). Assume there is
a risk-free asset. Show that a mean-variance frontier portfolio return is a pricing
factor. Clearly state definitions of terms and any assumptions you make.
34.  Derive a formula for the risk-free return when there is a representative investor
with CRRA utility and the change in log consumption is normally distributed.
35.  What is the form of Pareto optimal sharing rules when all investors have log
utility? Prove it.
